-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvKH4JQQgKZ31LxCb
AfZr+CSEmWz2b/JQdiWcuOZMcXqgCgYIKoZIzj0DAQehRANCAAQtZrk7hqoYglTu
U2Sb0jNLWZgR48lkB0uHwjHKdyr3A4YvpAPoDwrymatlIaBmqfPg7U8rqDEnCn8m
eHc9tJIn
-----END PRIVATE KEY-----