#!/bin/sh
set -e

# Add Homebrew to PATH (Xcode Cloud uses /Users/local/Homebrew)
export PATH="/Users/local/Homebrew/bin:/Users/local/Homebrew/sbin:$PATH"

echo ">>> Installing Node.js via Homebrew..."
brew install node || true   # non-fatal — may already be installed

echo ">>> Node version: $(node -v)"
echo ">>> npm version: $(npm -v)"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$SCRIPT_DIR/../../.."
PACKAGE_DIR="$SCRIPT_DIR/../CapApp-SPM"
RESOLVED_PATH="$SCRIPT_DIR/../App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"

echo ">>> Installing Node dependencies..."
cd "$APP_DIR"
npm install

echo ">>> Building web app..."
npm run build

echo ">>> Syncing Capacitor..."
npx cap sync ios

# ── Fix any Windows-style backslash paths regenerated by cap sync ─────────────
echo ">>> Fixing path separators in Package.swift (safety net)..."
sed -i '' 's|\\|/|g' "$PACKAGE_DIR/Package.swift" 2>/dev/null || true

# ── Update Linphone pin in the committed Package.resolved ─────────────────────
# We skip swift package resolve entirely — the committed Package.resolved already
# has all packages pinned. We only need to refresh the Linphone branch revision
# in case the stable branch HEAD moved since the last commit.
echo ">>> Fetching Linphone stable HEAD from GitHub mirror..."
LINPHONE_REVISION=$(git ls-remote https://github.com/oneeyedkingmktg/linphone-sdk-swift-ios-mirror.git refs/heads/stable 2>/dev/null | awk '{print $1}')

if [ -z "$LINPHONE_REVISION" ]; then
  echo ">>> WARNING: Could not fetch Linphone revision — keeping committed pin"
else
  echo ">>> Linphone stable HEAD: $LINPHONE_REVISION"
  python3 - "$RESOLVED_PATH" "$LINPHONE_REVISION" <<'PYEOF'
import json, sys
path, revision = sys.argv[1], sys.argv[2]
with open(path) as f:
    data = json.load(f)
data["pins"] = [p for p in data["pins"] if p.get("identity") != "linphone-sdk-swift-ios-mirror"]
data["pins"].append({
    "identity": "linphone-sdk-swift-ios-mirror",
    "kind": "remoteSourceControl",
    "location": "https://github.com/oneeyedkingmktg/linphone-sdk-swift-ios-mirror.git",
    "state": {"branch": "stable", "revision": revision}
})
data["pins"].sort(key=lambda p: p["identity"])
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
print(">>> Linphone pin injected successfully")
PYEOF
fi

echo ">>> Post-clone steps complete."
