-- ============================================================
-- v2 Schema Migration
-- 7 new tables — all additive, nothing modified or dropped
-- Safe to run on any environment
-- Run: psql $DATABASE_URL -f migrations/v2-schema.sql
-- ============================================================


-- ============================================================
-- 1. USER_TYPES
-- Flexible role/permission types per company.
-- Replaces hardcoded 'master'/'admin'/'user' role strings.
-- Each company defines their own types (salesman, installer, etc.)
-- Permissions stored as JSONB so new flags can be added without schema changes.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_types (
  id               SERIAL PRIMARY KEY,
  company_id       INTEGER REFERENCES companies(id) ON DELETE CASCADE,
  name             VARCHAR(50)  NOT NULL,
  display_name     VARCHAR(100) NOT NULL,
  is_system        BOOLEAN DEFAULT false,  -- true = cannot be deleted by company admin
  permissions      JSONB NOT NULL DEFAULT '{}',
  created_at       TIMESTAMP DEFAULT NOW(),
  updated_at       TIMESTAMP DEFAULT NOW(),
  UNIQUE(company_id, name)
);

-- Permission keys used in the JSONB object:
-- view_leads              — can see leads/contacts list
-- edit_leads              — can create and edit leads/contacts
-- view_jobs               — can see jobs
-- edit_jobs               — can create and edit jobs
-- view_own_jobs_only      — when true, restricts to only assigned jobs
-- view_financials         — can see contract prices and P&L data
-- view_time_entries       — can see time entry records
-- manage_own_time         — can clock in/out for themselves
-- manage_crew_time        — can clock in/out for other crew members
-- view_reports            — can access the reports section
-- manage_users            — can add and edit users
-- manage_settings         — can edit company settings
-- view_calendar           — can see the calendar
-- view_messages           — can see the messaging/conversations tab


-- ============================================================
-- 2. CREWS
-- Crew definitions per company.
-- A crew has a name, a color, a lead installer, and a GHL calendar.
-- Created before jobs so jobs can FK into crews.
-- ============================================================

CREATE TABLE IF NOT EXISTS crews (
  id                 SERIAL PRIMARY KEY,
  company_id         INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name               VARCHAR(100) NOT NULL,
  description        TEXT,
  color              VARCHAR(7) DEFAULT '#00875A',   -- hex color for UI display
  lead_installer_id  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ghl_calendar_id    VARCHAR(100),                   -- linked GHL calendar for scheduling
  is_active          BOOLEAN DEFAULT true,
  created_at         TIMESTAMP DEFAULT NOW(),
  updated_at         TIMESTAMP DEFAULT NOW(),
  deleted_at         TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crews_company ON crews(company_id);


-- ============================================================
-- 3. CREW_MEMBERS
-- Which users belong to which crew.
-- A user can be on multiple crews.
-- is_lead marks the lead installer for this specific crew.
-- ============================================================

CREATE TABLE IF NOT EXISTS crew_members (
  id          SERIAL PRIMARY KEY,
  crew_id     INTEGER NOT NULL REFERENCES crews(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  is_lead     BOOLEAN DEFAULT false,
  created_at  TIMESTAMP DEFAULT NOW(),
  UNIQUE(crew_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_crew_members_crew ON crew_members(crew_id);
CREATE INDEX IF NOT EXISTS idx_crew_members_user ON crew_members(user_id);


-- ============================================================
-- 4. JOBS
-- One or more jobs per contact (lead).
-- Each job is a separate scope of work with its own dates,
-- crew assignment, pricing, and GHL opportunity.
-- ============================================================

CREATE TABLE IF NOT EXISTS jobs (
  id                           SERIAL PRIMARY KEY,
  company_id                   INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  lead_id                      INTEGER NOT NULL REFERENCES leads(id) ON DELETE CASCADE,

  job_number                   VARCHAR(20),       -- e.g. PJ-2025-045, auto-generated by app
  job_name                     VARCHAR(255) NOT NULL,
  job_type                     VARCHAR(100),      -- e.g. 'Interior Painting', 'Epoxy Floor'
  status                       VARCHAR(50)  DEFAULT 'in_progress',
  priority                     VARCHAR(20)  DEFAULT 'normal',
  description                  TEXT,

  -- Job location (may differ from contact address)
  address                      VARCHAR(255),
  city                         VARCHAR(100),
  state                        VARCHAR(2),
  zip                          VARCHAR(10),

  -- Dates
  start_date                   DATE,
  target_completion_date       DATE,
  actual_completion_date       DATE,

  -- Financial
  contract_price               DECIMAL(10,2),
  default_hourly_rate          DECIMAL(8,2),
  overtime_rate                DECIMAL(8,2),
  billable                     BOOLEAN DEFAULT true,
  taxable                      BOOLEAN DEFAULT true,

  -- Job settings
  require_photos_at_completion BOOLEAN DEFAULT false,
  allow_crew_time_entry        BOOLEAN DEFAULT true,

  -- Primary assignments (single salesman + single crew for the common case)
  assigned_salesman_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
  primary_crew_id              INTEGER REFERENCES crews(id) ON DELETE SET NULL,

  -- GHL integration
  ghl_opportunity_id           VARCHAR(100),      -- GHL opportunity ID for this job

  -- Notes
  internal_notes               TEXT,

  -- Meta
  created_by_user_id           INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at                   TIMESTAMP DEFAULT NOW(),
  updated_at                   TIMESTAMP DEFAULT NOW(),
  deleted_at                   TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jobs_company    ON jobs(company_id);
CREATE INDEX IF NOT EXISTS idx_jobs_lead       ON jobs(lead_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status     ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_salesman   ON jobs(assigned_salesman_id);
CREATE INDEX IF NOT EXISTS idx_jobs_crew       ON jobs(primary_crew_id);


-- ============================================================
-- 5. JOB_ASSIGNMENTS
-- Additional user assignments beyond the primary salesman/crew on a job.
-- Supports multiple salesmen, multiple installers, etc.
-- ============================================================

CREATE TABLE IF NOT EXISTS job_assignments (
  id               SERIAL PRIMARY KEY,
  job_id           INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assignment_role  VARCHAR(50) NOT NULL,   -- 'salesman', 'installer', 'lead_installer'
  created_at       TIMESTAMP DEFAULT NOW(),
  UNIQUE(job_id, user_id, assignment_role)
);

CREATE INDEX IF NOT EXISTS idx_job_assignments_job  ON job_assignments(job_id);
CREATE INDEX IF NOT EXISTS idx_job_assignments_user ON job_assignments(user_id);


-- ============================================================
-- 6. TIME_ENTRIES
-- Clock in/out records per user per job.
-- hours_worked and labor_cost are stored on clock_out
-- for fast reporting queries without needing to recompute.
-- ============================================================

CREATE TABLE IF NOT EXISTS time_entries (
  id                       SERIAL PRIMARY KEY,
  company_id               INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  job_id                   INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  user_id                  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  clock_in                 TIMESTAMP NOT NULL,
  clock_out                TIMESTAMP,
  hours_worked             DECIMAL(6,2),    -- computed and stored when clocked out

  hourly_rate              DECIMAL(8,2),    -- rate snapshot at time of entry
  labor_cost               DECIMAL(10,2),   -- hours_worked * hourly_rate, stored on clock_out

  notes                    TEXT,

  -- Who performed the clock action (may differ from user if lead clocked in crew)
  clocked_in_by_user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  clocked_out_by_user_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,

  created_at               TIMESTAMP DEFAULT NOW(),
  updated_at               TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_time_entries_job     ON time_entries(job_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_user    ON time_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_company ON time_entries(company_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_clockin ON time_entries(clock_in);


-- ============================================================
-- 7. JOB_MATERIALS
-- Materials logged against a job for cost tracking.
-- total_cost is computed and stored (quantity * unit_cost).
-- ============================================================

CREATE TABLE IF NOT EXISTS job_materials (
  id                   SERIAL PRIMARY KEY,
  company_id           INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  job_id               INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,

  description          VARCHAR(255) NOT NULL,
  quantity             DECIMAL(8,2)  DEFAULT 1,
  unit_cost            DECIMAL(10,2) NOT NULL,
  total_cost           DECIMAL(10,2) GENERATED ALWAYS AS (quantity * unit_cost) STORED,

  added_by_user_id     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at           TIMESTAMP DEFAULT NOW(),
  updated_at           TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_materials_job ON job_materials(job_id);


-- ============================================================
-- ADD user_type_id TO users (additive column, nullable)
-- Links a user to a user_type for the v2 permission system.
-- Existing users keep working via the old role column until migrated.
-- ============================================================

ALTER TABLE users ADD COLUMN IF NOT EXISTS user_type_id INTEGER REFERENCES user_types(id) ON DELETE SET NULL;
